### ISSUE TITLE
Rename parameter `-Tags` to `-Tag`

### ISSUE THREAD

**Issue by jpawlowski** [PowerShell/CompatPowerShellGet#19]
In version 0.0.2, the `-Tag` parameter is translated to `-Tags` instead of `-Tag`:

````
Find-PSResource: A parameter cannot be found that matches parameter name 'Tags'.
````

This is not accepted by the latest versions of PowerShellGet and shall be fixed in CompatPowerShellGet.

**Comment by alerickson** [comment]
Thanks for opening this issue @jpawlowski!  This should be resolved as of the 0.0.4.  If you're still encountering this problem feel free to open up a new issue.
